### ISSUE TITLE
/examples out of date / no longer building or running

### ISSUE THREAD

**Issue by troygoode** [freezedev/moirai#10]
Hi @frostney,

When you updated `moirai` to use `react-scenedirector` you forgot to update the example code to use the new scene syntax (passing a hash into `<SceneDirector scenes={scenes} />` instead of as child elements).

I also had serious difficulties getting the example to build/run. `npm run build && npm run examples` didn't work for me (I ended up just copying the example code over to another project I have to run it). It looks to me like your babel transform isn't happening appropriately, but I'm not familiar enough with `rollup` to fix it right now.

TG

**Comment by frostney** [comment]
Thank you for reporting the issue and I'm sorry for the sub-par developer experience. I'm looking into this right now.
